# name: PayPal Ruby AUTO-RELEASE FLOW

# on:
#   push:
#     branches: [ main ]
#     tags:
#       - 'v*' # Trigger on tags like v0.1.0
#   pull_request:
#     branches: [ main ]

# jobs:
#   lint:
#     name: RuboCop Lint
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['3.2'] # Run lint on a recent stable Ruby version

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Ruby ${{ matrix.ruby-version }}
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: ${{ matrix.ruby-version }}
#         bundler-cache: true # Runs 'bundle install' and caches dependencies

#     - name: Run RuboCop
#       run: bundle exec rake rubocop # Or directly `bundle exec rubocop`

#   test:
#     name: Test on Ruby ${{ matrix.ruby-version }}
#     needs: lint # Run tests after lint passes
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3']

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Ruby ${{ matrix.ruby-version }}
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: ${{ matrix.ruby-version }}
#         bundler-cache: true

#     - name: Run tests
#       run: bundle exec rake test

#   # release:
#   #   name: Release to RubyGems.org
#   #   needs: test # Ensure tests pass before releasing
#   #   runs-on: ubuntu-latest
#   #   if: startsWith(github.ref, 'refs/tags/v') # Only run this job if a tag starting with 'v' was pushed

#   #   steps:
#   #   - name: Checkout code
#   #     uses: actions/checkout@v4

#   #   - name: Set up Ruby
#   #     uses: ruby/setup-ruby@v1
#   #     with:
#   #       ruby-version: '3.2' # Use a recent stable Ruby version for releasing
#   #       bundler-cache: true

#   #   - name: Build gem
#   #     run: bundle exec rake build # Gem will be in pkg/

#   #   - name: Publish to RubyGems.org
#   #     env:
#   #       RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }} # Use your existing secret name or create a new one
#   #     run: |
#   #       gem push pkg/paypal-*.gem # Use wildcard to match the built gem file name